#!/bin/sh

scripts_history="${XDG_CACHE_HOME:-$HOME/.cache}/scripts_history"

search_history="${XDG_CACHE_HOME:-$HOME/.cache}/search_history"

program_history="${XDG_CACHE_HOME:-$HOME/.cache}/program_history"

bookmark_history="${XDG_CACHE_HOME:-$HOME/.cache}/bookmark_history"

emoji_history="${XDG_CACHE_HOME:-$HOME/.cache}/emoji_history"

mounted_dev_cache="${XDG_CACHE_HOME:-$HOME/.cache}/mounted_devs"
