#!/bin/sh

menurc="${XDG_CONFIG_HOME:-$HOME/.config}/menurc"

bookmarks="${BOOKMARKS:-$HOME/linux/lib/bookmarks/bookmarks}"

bookmark_groups="${BOOKMARK_GROUPS:-$HOME/linux/lib/bookmarks/groups}"

search_engines="${SEARCH_ENGINE:-$HOME/linux/lib/search_engines}"

programs="${PROGRAM_LIST:-$HOME/.cache/dmenu_run}"

term_cmd="alacritty -e"

term_working_dir="alacritty --working-directory"

editor="nvim"

sudo_editor="sudoedit"

term_fm="lf"

wallpaper_setter="${XDG_CONFIG_HOME:-$HOME/.config}/set_wallpaper"

screenlayout_setter="${XDG_CONFIG_HOME:-$HOME/.config}/screenlayout"

wallpapers_dir="${WALLPAPERS_DIR:-/usr/share/wallpapers}"

wallpaper_presets="${WALLPAPER_PRESETS:-$HOME/linux/lib/wallpaper_presets}"

browserrc="${XDG_CONFIG_HOME:-$HOME/.config}/browserrc"

screenlayouts="${SCREENLAYOUTS:-$HOME/linux/lib/screenlayouts/screenlayouts}"

mount_pts_dir="$HOME/mnt"

wmrc="${XDG_CONFIG_HOME:-$HOME/.config}/wm"

