#!/bin/sh

. "$SCRIPTS_HOME/scriptsrc"
. "$lib/lines"
. "$lib/args"

extract() {
    dir=""

    files=""

    for arg in "$@"; do
        case $arg in
            --dir=*) 
                arg_value=$(get_arg_value "--dir=" "$arg")
                if [ -d "$arg_value" ]; then
                    dir=$arg_value
                else
                    mkdir -p "$arg_value" 2>/dev/null

                    if [ -d "$arg_value" ]; then
                        dir=$arg_value
                    fi
                fi
                ;;
            *)
                if [ -f "$arg" ]; then
                    files=$(list_add "$files" "$arg")
                fi
                ;;
        esac
    done

    IFS=$NL
    for file in $files; do
        case $file in
            *.tar|*.tar.xz)
                if [ -d "$dir" ]; then
                    tar xf "$file" -C "$dir"
                else
                    tar xf "$file"
                fi
                ;;
            *.tar.bz2|*.bz2|*.tbz2)
                if [ -d "$dir" ]; then
                    tar xjf "$file" -C "$dir"
                else
                    tar xjf "$file"
                fi
                ;;
            *.tar.gz|*.tgz)
                if [ -d "$dir" ]; then
                    tar xzf "$file" -C "$dir"
                else
                    tar xzf "$file"
                fi
                ;;
            *.rar)
                if [ -d "$dir" ]; then
                    unrar x "$file" "$dir"
                else
                    unrar x "$file"
                fi
                ;;
            *.gz)
                gzip "$file"
                ;;
            *.zip)
                if [ -d "$dir" ]; then
                    unzip "$file" -d "$dir"
                else
                    unzip "$file"
                fi
                ;;
            *.Z)
                uncompress "$file"
                ;;
            *.7z)
                if [ -d "$dir" ]; then
                    7z x "$file" -o"$dir"
                else
                    7z x "$file"
                fi
                ;;
            *.deb)
                if [ -d "$dir" ]; then
                    ar x --output "$dir" "$file"
                else
                    ar x "$file"
                fi
                ;;
            *.tar.zst)
                if [ -d "$dir" ]; then
                    unzstd --output-dir-flat "$dir" "$file"
                else
                    unzstd "$file"
                fi
                ;;      
            *) echo "Invalid: $file" ;;
        esac
    done
    unset IFS
}

