#!/bin/sh

. "$SCRIPTS_HOME/scriptsrc"
. "$lib/csv"
. "$lib/program"
. "$lib/lines"

get_name() {
    value "$1" --file="$lib/data/browsers" --index=1
}

get_cmd() {
    value "$1" --file="$lib/data/browsers" --index=2
}

get_new_tab_cmd() {
    value "$1" --file="$lib/data/browsers" --index=3
}

get_new_win_cmd() {
    value "$1" --file="$lib/data/browsers" --index=4
}

get_names() {
    get_column 1 --file="$lib/data/browsers"
}

get_installed_browsers() {
    browser_list=$(get_names)

    IFS=$NL
    for browser in $browser_list; do
        browser_cmd=$(get_cmd "$browser")

        if is_installed "$browser_cmd"; then
            new_browser_list=$(list_add "$new_browser_list" "$browser")
        fi
    done
    unset IFS

    echo "$new_browser_list"
}

