#!/bin/sh

. "${SCRIPTS_DIR:-${0%/*}/..}/scriptsrc"
. "$lib/lines"

get_clipboard() {
    selection="clipboard"

    case "$1" in
        "--primary") selection="primary" ;;
        "--secondary") selection="secondary" ;;
    esac

    xclip -selection "$selection" -o 2>/dev/null
}

set_clipboard() {
    selection="clipboard"
    trailing_new_line="false"

    clipboard=""

    for arg in "$@"
    do
        case "$arg" in
            "--primary") selection="primary" ;;
            "--secondary") selection="secondary" ;;
            "--trailing-new-line") trailing_new_line="true" ;;
            *) clipboard=$(list_add "$clipboard" "$arg") ;;
        esac
    done

    if [ "$trailing_new_line" = "true" ]
    then
        echo "$clipboard" | xclip -selection "$selection"
    else
        printf "%s" "$clipboard" | xclip -selection "$selection"
    fi
}

