#!/bin/sh

. "$SCRIPTS_HOME/scriptsrc"
. "$lib/program"
. "$lib/lines"

find_cmd() {
    if [ "$(installed fd)" = "true" ]
    then
        use_fd="true"
    else
        use_fd="false"
    fi

    IFS="
"
    if [ "$use_fd" = "true" ]
    then
        fd . $1 -H -I -t f
    else
        find ${1:-.} -type f
    fi
    unset IFS
}

set_value() {
    if [ -s "$2" ]
    then
        sed -i '1,$d' "$2"
    fi

    echo "$1" >> "$2"
}

create_file() {
    if [ ! -e "$1" ]
    then
        case "$1" in
            *"/"*) mkdir -p "${1%/*}" ;;
        esac

        printf "" > "$1"
    fi
}

create_script_file() {
    if [ ! -e "$1" ]
    then
        case "$1" in
            *"/"*) mkdir -p "${1%/*}" ;;
        esac

        echo '#!/bin/sh' > "$1" && chmod +x "$1"
    fi
}

