#!/bin/sh

. "$SCRIPTS_HOME/scriptsrc"
. "$lib/program"
. "$lib/lines"
. "$lib/args"

find_cmd() {
    if [ "$(installed fd)" = "true" ]
    then
        use_fd="true"
    else
        use_fd="false"
    fi

    dirs=""
    args=""

    for arg in "$@"
    do
        case "$arg" in
            --include-hidden)
                if [ "$use_fd" = "true" ]
                then
                    args="$args -H -I"
                fi
                ;;
            --non-recursive)
                if [ "$use_fd" = "true" ]
                then
                    args="$args -d 1"
                else
                    args="$args -maxdepth 1"
                fi
                ;;
            *) 
                if [ -d "$arg" ]
                then
                    dirs=$(list_add "$dirs" "$arg")
                fi
                ;;
        esac
    done

    IFS="
"
    if [ "$use_fd" = "true" ]
    then
        eval fd . $dirs $args -t f
    else
        eval find ${dirs:-.} $args -type f
    fi
    unset IFS
}

set_value() {
    if [ -s "$2" ]
    then
        sed -i '1,$d' "$2"
    fi

    echo "$1" >> "$2"
}

create_file() {
    if [ ! -e "$1" ]
    then
        case "$1" in
            *"/"*) mkdir -p "${1%/*}" ;;
        esac

        printf "" > "$1"
    fi
}

create_script_file() {
    if [ ! -e "$1" ]
    then
        case "$1" in
            *"/"*) mkdir -p "${1%/*}" ;;
        esac

        echo '#!/bin/sh' > "$1" && chmod +x "$1"
    fi
}

