#!/bin/sh

. "$SCRIPTS_HOME/scriptsrc"
. "$lib/var/config"

is_installed() {
    if [ "$(command -v "$1")" ]; then
        return 0
    else
        return 1
    fi
}

is_not_installed() {
    if [ "$(command -v "$1")" ]; then
        return 1
    else
        return 0
    fi
}

is_running() {
    if pgrep -x "$1" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

is_not_running() {
    if pgrep -x "$1" >/dev/null 2>&1; then
        return 1
    else
        return 0
    fi
}

sync_program_cache() {
    IFS=:
    if stest -dqr -n "$programs" $PATH; then
        stest -flx $PATH | sort -u > "$programs"
    fi
    unset IFS
}

