#!/bin/sh

installed() {
    [ "$(command -v "$1")" ] && return 0 || return 1
}

sync_program_file() {
    IFS=:
    if stest -dqr -n "$1" $PATH; then
        stest -flx $PATH | sort -u > "$1"
    fi
    unset IFS
}

