#!/bin/sh

installed() {
    if [ "$(command -v "$1")" ]; then
        return 0
    else
        return 1
    fi
}

sync_program_file() {
    IFS=:
    if stest -dqr -n "$1" $PATH; then
        stest -flx $PATH | sort -u > "$1"
    fi
    unset IFS
}

