#!/bin/awk -f

/\.[Mm][Pp]4$|\
\.[Ww][Ee][Bb][Mm]$|\
\.[Gg][Ii][Ff]$|\
\.[Aa][Vv][Ii]$|\
\.[Ww][Ee][Mv]$|\
\.[Aa][Mm][Vv]$|\
\.[Ff][Ll][Vv]$|\
\.[Vv][Oo][Bb]$|\
\.[Oo][Gg][Vv]$|\
\.[Oo][Gg][Gg]$|\
\.[Dd][Rr][Cc]$|\
\.[Gg][Ii][Ff]$|\
\.[Gg][Ii][Ff][Vv]$|\
\.[Mm][Nn][Gg]$|\
\.[Mm][Oo][Vv]$|\
\.[Ww][Mm][Vv]$|\
\.[Mm][Tt][Ss]$|\
\.[Mm]2[Tt][Ss]$|\
\.TS$|\
\.[Mm][Oo][Vv]$|\
\.[Qq][Tt]$|\
\.[Yy][Uu][Vv]$|\
\.[Rr][Mm]$|\
\.[Rr][Mm][Vv][Bb]$|\
\.[Vv][Ii][Vv]$|\
\.[Aa][Ss][Ff]$|\
\.[Mm]4[Pp]$|\
\.[Mm]4[Vv]$|\
\.[Mm][Pp][Gg]$|\
\.[Mm][Pp][Ee][Gg]$|\
\.[Mm][Pp][Vv]$|\
\.[Mm][Pp][Ee]$|\
\.[Mm][Pp]2$|\
\.[Mm]2[Vv]$|\
\.[Ss][Vv][Ii]$|\
\.3[Gg][Pp]$|\
\.3[Gg]2$|\
\.[Mm][Xx][Ff]$|\
\.[Rr][Oo][Qq]$|\
\.[Nn][Ss][Vv]$|\
\.[Ff]4[Vv]$|\
\.[Ff]4[Pp]$|\
\.[Ff]4[Aa]$|\
\.[Ff]4[Bb]$\
/
